### ISSUE TITLE
request support for composer 2.0 and php8

### ISSUE THREAD

**Issue by haohetao** [fxpio/composer-asset-plugin#336]

**Comment by Ferikl** [comment]
Have some issues with composer 2:
root@admin:/app# composer install
The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

Problem 1
- fxp/composer-asset-plugin is locked to version v1.4.6 and an update of this package was not requested.
- fxp/composer-asset-plugin v1.4.6 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.

**Comment by forevermatt** [comment]
Composer 2 support has a separate issue:
https://github.com/fxpio/composer-asset-plugin/issues/334#issuecomment-720125443
